-- (구버전) store_keywords 테이블 — 신규 설치는 keywords_schema.sql 사용 권장
-- 테이블명을 바꾼 경우 STORE_KEYWORDS_TABLE 환경변수와 맞추세요.

create table if not exists public.store_keywords (
  id bigint generated by default as identity primary key,
  category text not null,
  keyword text not null,
  monthly_search_volume integer default 0,
  competition_index numeric default 0,
  updated_at timestamptz default now(),
  unique (category, keyword)
);

create index if not exists idx_store_keywords_category_volume
  on public.store_keywords (category, monthly_search_volume desc);

-- anon/service role에 맞게 RLS 정책을 추가하세요.
-- 예: alter table public.store_keywords enable row level security;
